// eg: donglang

func int getV1() {
	return 1;
}

func int getInt() {
}
func void getVoid() {
}
func int* getPtr() {
}

func int[] getArr(int *p, int[] arr, int[][2] aarr1) {
	//int[2] rArr;
	//return rArr;
}

func int main(){
	int a, b;
	int* pa, pb;
	int** ppa, ppb;
	int[1] arr1;
	int[2][2] arr2;

	//arr1 = pa;
	pa = arr1;
	a = **ppa;
	a = ppa[1][1];
	a = arr2[1][1];

	getArr( arr1, pa, arr2);
	printf("hello world a:%d\n", **ppa);
	return 0;
}
